name: Download FFmpeg Decoder AAR

on:
  workflow_dispatch:

jobs:
  download-ffmpeg-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Create output folder
        run: mkdir -p out

      - name: Download Jellyfin Media3 FFmpeg decoder AAR
        run: |
          curl -L \
            "https://repo1.maven.org/maven2/org/jellyfin/media3/media3-ffmpeg-decoder/1.9.0+1/media3-ffmpeg-decoder-1.9.0+1.aar" \
            -o out/media3-ffmpeg-decoder-1.9.0+1.aar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: media3-ffmpeg-decoder-aar
          path: out/*.aar
