name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate release keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-key.jks \
            -storepass "${{ secrets.SIGNING_STORE_PASSWORD }}" \
            -keypass "${{ secrets.SIGNING_KEY_PASSWORD }}" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias "${{ secrets.SIGNING_KEY_ALIAS }}" \
            -dname "CN=Joy, OU=Joy, O=Joy, L=Mymensingh, ST=Dhaka, C=BD"

      - name: Convert keystore to Base64
        run: |
          base64 -w 0 release-key.jks > release-key-base64.txt

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore-files
          path: |
            release-key.jks
            release-key-base64.txt
